#+title: Tutorials on syedra-vision Package
#+author: Haldun Komsuoglu


Tutorials folder contains a collection of scripts demonstrating the
use of the package. Each script is a stand alone executable.

The scripts should be executed from the top project folder and from
within the development virtual environment and/or a setup where the
syedra package is installed.

#+begin_src sh
source venv/bin/activate
#+end_src

For instance, the ``tutorial/block/wrapper.py`` example can be executed
as follows:

#+begin_src sh
python -m tutorials.camera.capture
#+end_src

If the code is being executed at a remote machine the X
window display needs to be forwarded to the X server (most
likely on the user's computer). In this case the following
needs to be setup prior to code execution:

  - On the _user machine_ where the windows will be displayed
    the X Server on the receiving machine needs to add the
    remote machine as a permitted client. Alternatively,
    all external connection can be allowed as a shortcut.

#+begin_src sh
xhost +
#+end_src
    
  - On the _remote machine_ where the code will be executed
    The DISPLAY environment variable needs to be setup to
    direct the display connection to the X server. In the
    following example *<x-server-ip>* is the IP address of
    the receiving machine as seen by the remote machine.

#+begin_src sh
export DISPLAY=<x-server-ip>:0
#+end_src

To test the connection you can run *xeyes* command on the
remote machine in the command line.

#+begin_src sh
xeyes
#+end_src

* Camera

  - [[file:camera/capture.py][capture.py]] : captures a single image frame from a camera
    
* Display
* Keyboard
* Transform

  - [[file:transform/crop.py][crop.py]] : captures a frame from camera and crops the image
  - [[file:transform/convert.py][convert.py]] : captures a frame and converts the color model to HSV
    
* Detect

  - [[file:tutorials/detect/mask.py][mask.py]] : captures a frame and produces a HSV hue mask
  - [[file:detect/blob.py][blob.py]] : captures a frame and identifies the largest blob based on color
